from __future__ import annotations


def _group(*labels: str) -> tuple[str, ...]:
    return tuple(labels)


DEFAULT_WORLD_LABEL_GROUPS: tuple[tuple[str, ...], ...] = (
    _group(
        "person",
        "face",
        "head",
        "hand",
        "arm",
        "leg",
        "foot",
        "shoe",
        "boot",
        "slipper",
        "sandal",
        "sock",
        "glove",
        "hat",
        "cap",
        "helmet",
        "scarf",
        "mask",
        "sunglasses",
        "eyeglasses",
    ),
    _group(
        "shirt",
        "t shirt",
        "jacket",
        "coat",
        "hoodie",
        "sweater",
        "vest",
        "dress",
        "skirt",
        "jeans",
        "pants",
        "shorts",
        "belt",
        "tie",
        "backpack",
        "handbag",
        "purse",
        "wallet",
        "watch",
        "bracelet",
    ),
    _group(
        "chair",
        "office chair",
        "stool",
        "bench",
        "sofa",
        "couch",
        "loveseat",
        "ottoman",
        "bean bag",
        "table",
        "desk",
        "coffee table",
        "side table",
        "dining table",
        "nightstand",
        "cabinet",
        "drawer",
        "dresser",
        "wardrobe",
        "closet",
    ),
    _group(
        "shelf",
        "bookshelf",
        "rack",
        "stand",
        "tv stand",
        "console table",
        "storage box",
        "container",
        "basket",
        "bin",
        "bucket",
        "trash can",
        "recycling bin",
        "crate",
        "case",
        "toolbox",
        "safe",
        "locker",
        "cart",
        "trolley",
    ),
    _group(
        "bed",
        "mattress",
        "pillow",
        "blanket",
        "comforter",
        "bedsheet",
        "duvet",
        "quilt",
        "headboard",
        "crib",
        "bunk bed",
        "hamper",
        "laundry basket",
        "mirror",
        "vanity",
        "curtain",
        "blinds",
        "rug",
        "carpet",
        "mat",
    ),
    _group(
        "door",
        "doorknob",
        "window",
        "window frame",
        "windowsill",
        "wall",
        "ceiling",
        "floor",
        "stairs",
        "railing",
        "pillar",
        "beam",
        "fireplace",
        "picture frame",
        "wall art",
        "painting",
        "poster",
        "clock",
        "calendar",
        "whiteboard",
    ),
    _group(
        "monitor",
        "screen",
        "laptop",
        "desktop computer",
        "keyboard",
        "mouse",
        "mouse pad",
        "tablet",
        "cell phone",
        "phone",
        "smartphone",
        "printer",
        "scanner",
        "speaker",
        "webcam",
        "camera",
        "microphone",
        "headphones",
        "earbuds",
        "remote control",
    ),
    _group(
        "router",
        "modem",
        "power strip",
        "charger",
        "charging cable",
        "usb drive",
        "hard drive",
        "game console",
        "controller",
        "television",
        "projector",
        "projector screen",
        "lamp",
        "desk lamp",
        "table lamp",
        "floor lamp",
        "light bulb",
        "fan",
        "air conditioner",
        "heater",
    ),
    _group(
        "book",
        "notebook",
        "paper",
        "document",
        "folder",
        "binder",
        "box file",
        "clipboard",
        "envelope",
        "magazine",
        "newspaper",
        "journal",
        "sticky note",
        "index card",
        "pen",
        "pencil",
        "marker",
        "highlighter",
        "eraser",
        "sharpener",
    ),
    _group(
        "ruler",
        "scissors",
        "stapler",
        "tape dispenser",
        "glue bottle",
        "paper clip",
        "push pin",
        "calculator",
        "stamp",
        "ink pad",
        "desk organizer",
        "file organizer",
        "pencil case",
        "notepad",
        "planner",
        "diary",
        "certificate",
        "folder tray",
        "document tray",
        "label maker",
    ),
    _group(
        "cup",
        "mug",
        "glass",
        "bottle",
        "plate",
        "bowl",
        "spoon",
        "fork",
        "knife",
        "napkin",
        "tray",
        "kettle",
        "teapot",
        "coffee maker",
        "water dispenser",
        "thermos",
        "lunch box",
        "food container",
        "bottle opener",
        "cutting board",
    ),
    _group(
        "refrigerator",
        "microwave",
        "oven",
        "stove",
        "toaster",
        "blender",
        "mixer",
        "rice cooker",
        "pressure cooker",
        "pan",
        "pot",
        "dish rack",
        "sink",
        "faucet",
        "soap dispenser",
        "dish soap",
        "sponge",
        "towel",
        "paper towel",
        "trash bag",
    ),
    _group(
        "toilet",
        "toilet paper",
        "toothbrush",
        "toothpaste",
        "shampoo bottle",
        "soap bar",
        "bathtub",
        "shower curtain",
        "shower head",
        "bath towel",
        "hand towel",
        "bath mat",
        "hair dryer",
        "razor",
        "comb",
        "brush",
        "cosmetic bag",
        "makeup mirror",
        "medicine bottle",
        "first aid kit",
    ),
    _group(
        "plant",
        "flower pot",
        "vase",
        "bouquet",
        "tree",
        "bush",
        "grass",
        "leaf",
        "branch",
        "flower",
        "cactus",
        "succulent",
        "garden pot",
        "watering can",
        "garden hose",
        "shovel",
        "rake",
        "lawn mower",
        "fence",
        "gate",
    ),
    _group(
        "car",
        "bicycle",
        "motorcycle",
        "scooter",
        "bus",
        "truck",
        "van",
        "taxi",
        "train",
        "tram",
        "airplane",
        "helicopter",
        "boat",
        "ship",
        "canoe",
        "kayak",
        "skateboard",
        "roller skates",
        "traffic light",
        "traffic cone",
    ),
    _group(
        "road",
        "street",
        "sidewalk",
        "crosswalk",
        "bridge",
        "tunnel",
        "building",
        "house",
        "apartment building",
        "garage",
        "warehouse",
        "factory",
        "office building",
        "school building",
        "hospital building",
        "storefront",
        "parking meter",
        "mailbox",
        "street sign",
        "billboard",
    ),
    _group(
        "dog",
        "cat",
        "bird",
        "horse",
        "cow",
        "sheep",
        "goat",
        "pig",
        "rabbit",
        "hamster",
        "mouse animal",
        "squirrel",
        "deer",
        "elephant",
        "zebra",
        "giraffe",
        "bear",
        "lion",
        "tiger",
        "monkey",
    ),
    _group(
        "fish",
        "turtle",
        "frog",
        "snake",
        "lizard",
        "chicken",
        "duck",
        "goose",
        "owl",
        "eagle",
        "parrot",
        "pigeon",
        "crow",
        "butterfly",
        "bee",
        "ant",
        "spider",
        "insect",
        "pet bed",
        "pet bowl",
    ),
    _group(
        "apple",
        "banana",
        "orange",
        "grapes",
        "watermelon",
        "strawberry",
        "pineapple",
        "mango",
        "lemon",
        "tomato",
        "potato",
        "onion",
        "carrot",
        "broccoli",
        "cucumber",
        "egg",
        "bread",
        "cake",
        "cookie",
        "sandwich",
    ),
    _group(
        "pizza",
        "burger",
        "hot dog",
        "fries",
        "salad",
        "rice",
        "noodles",
        "pasta",
        "soup",
        "ice cream",
        "candy",
        "chocolate",
        "chips",
        "snack bag",
        "juice box",
        "milk carton",
        "soda can",
        "wine glass",
        "beer bottle",
        "fruit bowl",
    ),
    _group(
        "hammer",
        "screwdriver",
        "wrench",
        "pliers",
        "drill",
        "saw",
        "measuring tape",
        "ladder",
        "paint bucket",
        "paint brush",
        "safety helmet",
        "work gloves",
        "tool belt",
        "nail box",
        "screw box",
        "flashlight",
        "extension cord",
        "generator",
        "workbench",
        "vise",
    ),
    _group(
        "broom",
        "mop",
        "vacuum cleaner",
        "dustpan",
        "spray bottle",
        "cleaning cloth",
        "detergent bottle",
        "bleach bottle",
        "bucket mop",
        "squeegee",
        "scrub brush",
        "iron",
        "ironing board",
        "sewing machine",
        "clothes hanger",
        "garment rack",
        "shoe rack",
        "umbrella",
        "walking stick",
        "shopping bag",
    ),
    _group(
        "soccer ball",
        "basketball",
        "baseball",
        "tennis ball",
        "tennis racket",
        "badminton racket",
        "golf club",
        "golf ball",
        "cricket bat",
        "cricket ball",
        "football",
        "volleyball",
        "frisbee",
        "yoga mat",
        "dumbbell",
        "barbell",
        "treadmill",
        "bicycle helmet",
        "skipping rope",
        "boxing gloves",
    ),
    _group(
        "guitar",
        "piano",
        "keyboard instrument",
        "violin",
        "drum",
        "microphone stand",
        "speaker stand",
        "music stand",
        "sheet music",
        "amplifier",
        "trumpet",
        "flute",
        "saxophone",
        "clarinet",
        "ukulele",
        "record player",
        "radio",
        "cd player",
        "television remote",
        "stage light",
    ),
    _group(
        "toy car",
        "toy train",
        "doll",
        "teddy bear",
        "building blocks",
        "puzzle box",
        "board game",
        "playing cards",
        "balloon",
        "kite",
        "stuffed animal",
        "action figure",
        "toy robot",
        "toy airplane",
        "toy dinosaur",
        "lego box",
        "baby stroller",
        "baby bottle",
        "pacifier",
        "baby toy",
    ),
    _group(
        "school bag",
        "chalkboard",
        "desk bench",
        "classroom chair",
        "school bus",
        "globe",
        "map",
        "science model",
        "lab coat",
        "beaker",
        "test tube",
        "microscope",
        "graduation cap",
        "student id card",
        "exam paper",
        "report card",
        "library shelf",
        "attendance register",
        "chalk",
        "project notebook",
    ),
    _group(
        "hospital bed",
        "wheelchair",
        "stretcher",
        "syringe",
        "thermometer",
        "stethoscope",
        "blood pressure monitor",
        "medicine box",
        "pill bottle",
        "oxygen cylinder",
        "hospital curtain",
        "iv stand",
        "bandage",
        "face shield",
        "surgical mask",
        "doctor coat",
        "nurse station desk",
        "medical chart",
        "x ray film",
        "sanitizer bottle",
    ),
    _group(
        "cash register",
        "barcode scanner",
        "shopping cart",
        "shopping basket",
        "display shelf",
        "mannequin",
        "price tag",
        "clothing rack",
        "checkout counter",
        "gift box",
        "wrapping paper",
        "jewelry stand",
        "necklace",
        "ring box",
        "cosmetic bottle",
        "perfume bottle",
        "shoe box",
        "grocery bag",
        "fruit crate",
        "bakery tray",
    ),
    _group(
        "forklift",
        "pallet",
        "shipping box",
        "barrel",
        "oil drum",
        "pipe",
        "valve",
        "control panel",
        "server rack",
        "circuit board",
        "robot arm",
        "conveyor belt",
        "machine",
        "compressor",
        "welding mask",
        "safety cone",
        "industrial fan",
        "metal shelf",
        "storage pallet",
        "work cart",
    ),
    _group(
        "beach umbrella",
        "beach chair",
        "surfboard",
        "tent",
        "camping chair",
        "sleeping bag",
        "campfire",
        "picnic table",
        "cooler box",
        "fishing rod",
        "life jacket",
        "binoculars",
        "map board",
        "mountain bike",
        "park bench",
        "playground slide",
        "swing",
        "seesaw",
        "sandbox",
        "fountain",
    ),
    _group(
        "statue",
        "flag",
        "banner",
        "podium",
        "trophy",
        "medal",
        "certificate frame",
        "book stack",
        "newspaper stand",
        "display board",
        "notice board",
        "server monitor",
        "air purifier",
        "humidifier",
        "dehumidifier",
        "coffee table book",
        "floor cushion",
        "throw pillow",
        "desk mat",
        "coaster",
    ),
)

